#! /bin/sh

help_message() {
	echo "usage: goto [-h] bookmark"
	echo ""
	echo "navigate to a bookmarked location created using the 'mark' command"
	echo ""
	echo "positional arguments:"
	echo "  bookmark 	a name of the bookmark to navigate to or execute"
	echo ""
	echo "optional arguments:"
	echo "-h, --help 	show this help message and exit"
	echo ""
	echo "see also: mark, unmark"
}

# Parse options
while [ $# -gt 0 ]
do
    case "$1" in
    	(-h) help_message;;
    	(--help) help_message;;
    	(-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    	(*)  break;;
    esac
    shift
done

# Parse arguments
if [[ "$#" == "0" ]]; then
	echo "error: you must supply a name for the bookmark" 1>&2; exit 1;
elif (( $# > 1)); then
	echo "error: too many arguments" 1>&2; exit 1;
else
	MARK="$1"
	shift
fi



marks=()
found=false
if [ -f ~/.bookmarks ]; then
	while read line    
	do    
		split=(${line//:/ })
		SAVED_MARK=${split[0]}
		LOCATION=${split[1]}
		if [ $SAVED_MARK = $MARK ]; then
			if [ -d $LOCATION ]; then
				cd $LOCATION;
				found=true
			elif [-f $LOCATION ]; then
				$LOCATION;
				found=true
			else
				echo "error: invalid bookmark" 1>&2;
				found=true
			fi
			break;
		fi
	done < ~/.bookmarks
fi

if [ $found = false ]; then
	echo "error: bookmark not found" 1>&2
fi

