#! /bin/sh

help_message() {
	echo "usage: unmark [-h] bookmark"
	echo ""
	echo "remove a bookmarked location created using the 'mark' command"
	echo ""
	echo "positional arguments:"
	echo "  bookmark 	a name of the bookmark to remove"
	echo ""
	echo "optional arguments:"
	echo "-h, --help 	show this help message and exit"
	echo ""
	echo "see also: mark, goto"
}

# parse options
A_FLAG=false
while [ $# -gt 0 ]
do
    case "$1" in
    	(-h) help_message; exit 0;;
    	(-a) A_FLAG=true;;
    	(--help) help_message; exit 0;;
    	(-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    	(*)  break;;
    esac
    shift
done

if [ "$#" == "0" -a $A_FLAG = false ]; then
	echo "error: you must supply a name for the bookmark" 1>&2; exit 1;
fi

# parse arguments
NEW_MARK="$1"
shift

if  (($# > 0)); then
	echo "error: too many arguments" 1>&2; exit 1;
fi

# accumulate all bookmarks other than one selected for removal
marks=()
if [ -f ~/.bookmarks ]; then
	while read line    
	do    
		split=(${line//:/ })
		SAVED_MARK=${split[0]}
		if [ ! $SAVED_MARK = "$NEW_MARK" -a "$A_FLAG" = false ]; then
			marks+=($line)
		fi
	done < ~/.bookmarks
fi

# replace old bookmark file with new contents
rm -rf ~/.bookmarks
touch ~/.bookmarks
for mark in ${marks[@]}; do
	echo $mark >> ~/.bookmarks
done


	

